export const productDemoStyles = `
:host{--pd-accent:#0a84ff;--pd-blue:#0071e3;--pd-bg:#f5f5f7;--pd-card:#fffc;--pd-bar:#fffffff0;--pd-fg:#1d1d1f;--pd-muted:#6e6e73;--pd-line:#0000001a;display:inline-block;color:var(--pd-fg);font:400 15px/1.45 -apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",sans-serif;-webkit-font-smoothing:antialiased}
:host([external-trigger]){display:contents}:host([external-trigger]) .launch,[hidden]{display:none!important}*,*:before,*:after{box-sizing:border-box}button,input{color:inherit;font:inherit}button{-webkit-tap-highlight-color:transparent}
.launch,.primary,.send{border:0;background:var(--pd-blue);color:#fff;font-weight:650;cursor:pointer}.launch{min-height:44px;padding:11px 20px;border-radius:99px;box-shadow:0 8px 24px #0071e338}.launch:active,.primary:active{transform:scale(.98)}
.shell{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:center;padding:clamp(12px,2.6vw,32px);background:#0c0c0e9e;backdrop-filter:blur(22px);opacity:0;transition:opacity .24s ease;overscroll-behavior:contain}.shell[data-open=true]{opacity:1}
.panel{width:min(1240px,100%);height:min(820px,calc(100dvh - clamp(24px,5.2vw,64px)));min-height:480px;overflow:hidden;display:grid;grid-template-rows:62px minmax(0,1fr) 72px;background:var(--pd-card);border:1px solid #ffffff6b;border-radius:24px;box-shadow:0 40px 100px #0006;transform:translateY(14px) scale(.98);transition:transform .32s cubic-bezier(.16,1,.3,1)}.shell[data-open=true] .panel{transform:none}
.top,.composer{display:flex;align-items:center;border-color:var(--pd-line);background:var(--pd-bar);backdrop-filter:blur(18px)}.top{gap:12px;padding:0 12px 0 20px;border-bottom:1px solid var(--pd-line)}.brand,.status-wrap{min-width:0;display:flex;align-items:center;gap:9px}.mark{width:30px;height:30px;display:grid;place-items:center;flex:none;border-radius:9px;background:linear-gradient(145deg,#45a8ff,#0879e8);box-shadow:inset 0 1px #ffffff66,0 4px 12px #0a84ff3d;color:#fff}.mark svg{width:17px}.title{overflow:hidden;font-weight:650;letter-spacing:-.015em;text-overflow:ellipsis;white-space:nowrap}.status-wrap{margin-left:auto;color:var(--pd-muted);font-size:13px}.status{max-width:min(42vw,500px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status-dot{width:7px;height:7px;flex:none;border-radius:50%;background:#8e8e93;box-shadow:0 0 0 3px #8e8e931f}:host([data-status=active]) .status-dot,:host([data-status=complete]) .status-dot{background:#30d158}:host([data-status=loading]) .status-dot,:host([data-status=reconnecting]) .status-dot{background:#ff9f0a;animation:pulse 1.4s ease-in-out infinite}:host([data-status=error]) .status-dot{background:#ff453a}
.close,.send{width:42px;height:42px;display:grid;place-items:center;flex:none;border:0;border-radius:50%;cursor:pointer}.close{margin-left:2px;background:transparent;color:var(--pd-muted)}.close:hover{background:#0000000f}.close svg,.send svg{width:18px}
.stage{--pd-focus-x:50%;--pd-focus-y:50%;--pd-focus-scale:1;position:relative;min-height:0;overflow:hidden;contain:layout paint;background:var(--pd-bg)}.stage iframe{width:100%;height:100%;display:block;border:0;background:#fff;opacity:0;transform:scale(1);transform-origin:var(--pd-focus-x) var(--pd-focus-y);transition:opacity .26s ease,transform .68s cubic-bezier(.16,1,.3,1);will-change:transform}.stage[data-viewer-ready=true] iframe{opacity:1}.stage[data-focused=true] iframe{transform:scale(var(--pd-focus-scale))}.stage:after{position:absolute;inset:0;pointer-events:none;background:radial-gradient(circle at var(--pd-focus-x) var(--pd-focus-y),transparent 20%,#0003 100%);content:"";opacity:0;transition:opacity .36s}.stage[data-focused=true]:after{opacity:1}
.empty,.goal{position:absolute;inset:0;display:grid;place-items:center;padding:24px;background:radial-gradient(circle at 50% 10%,#0a84ff1f,transparent 36%),var(--pd-bg)}.empty{z-index:2;text-align:center}.loader-glyph{width:56px;height:56px;margin:0 auto 18px;position:relative;display:grid;place-items:center;border-radius:18px;background:var(--pd-card);box-shadow:0 12px 36px #0002;color:var(--pd-accent)}.loader-glyph:before{position:absolute;inset:-6px;border:2px solid transparent;border-top-color:var(--pd-accent);border-radius:22px;content:"";animation:spin 1.1s linear infinite}.loader-glyph svg{width:25px}.loader strong{display:block;margin-bottom:6px;font-size:17px}.loader p{min-height:42px;margin:0;color:var(--pd-muted);font-size:14px}.progress{width:160px;height:4px;margin:18px auto 0;overflow:hidden;border-radius:9px;background:#0002}.progress:after{width:42%;height:100%;display:block;border-radius:inherit;background:var(--pd-accent);content:"";animation:progress 1.4s ease-in-out infinite}
.goal{z-index:3}.goal form{width:min(560px,100%);padding:clamp(24px,4vw,38px);border:1px solid #ffffffbd;border-radius:24px;background:var(--pd-card);box-shadow:0 20px 60px #0002;backdrop-filter:blur(24px)}.kicker{margin:0 0 10px;color:var(--pd-blue);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}.goal h2{margin:0;font-size:clamp(26px,4vw,38px);line-height:1.08;letter-spacing:-.045em}.copy{margin:12px 0 24px;color:var(--pd-muted);font-size:16px}.label{display:block;margin:0 0 8px 2px;font-size:13px;font-weight:600}
.goal input,.composer input{width:100%;min-width:0;border:1px solid #0002;outline:0;border-radius:13px;background:#ffffffe8;transition:border-color .16s,box-shadow .16s}.goal input{min-height:50px;padding:13px 15px}.goal input:focus,.composer input:focus{border-color:var(--pd-accent);box-shadow:0 0 0 4px #0a84ff24}.primary{width:100%;min-height:50px;margin-top:12px;border-radius:13px}.primary:disabled{cursor:wait;opacity:.6}.notice{min-height:20px;margin:10px 2px 0;color:#d70015;font-size:13px}
.composer{gap:10px;padding:10px 12px 10px 16px;border-top:1px solid var(--pd-line)}.composer input{height:46px;flex:1;padding:11px 14px}.send{width:46px;height:46px}.send:disabled,.composer input:disabled{cursor:not-allowed;opacity:.4}.launch:focus-visible,.close:focus-visible,.primary:focus-visible,.send:focus-visible{outline:3px solid #0a84ff7a;outline-offset:3px}
@keyframes spin{to{transform:rotate(360deg)}}@keyframes progress{from{transform:translateX(-120%)}to{transform:translateX(240%)}}@keyframes pulse{50%{box-shadow:0 0 0 5px #ff9f0a14}}
@media(prefers-color-scheme:dark){:host{--pd-bg:#18181a;--pd-card:#2c2c2ee8;--pd-bar:#1e1e20e8;--pd-fg:#f5f5f7;--pd-muted:#a1a1a6;--pd-line:#ffffff1c}.panel{border-color:#ffffff24}.goal form{border-color:#ffffff20}.goal input,.composer input{border-color:#ffffff1f;background:#2c2c2ef2}}
@media(max-width:680px){.shell{padding:0}.panel{width:100%;height:100dvh;min-height:0;grid-template-rows:58px minmax(0,1fr) 66px;border:0;border-radius:0}.top{padding-left:14px}.mark{width:28px;height:28px}.status{max-width:26vw}.goal{padding:16px}.goal form{padding:24px 20px;border-radius:20px}.goal h2{font-size:29px}.copy{font-size:15px}.composer{padding:9px 10px}}
@media(prefers-reduced-motion:reduce){.shell,.panel,.stage iframe,.stage:after,.launch,.primary,.send,.status-dot{animation:none!important;transition-duration:.01ms!important}.loader-glyph:before,.progress:after{animation:none}.progress:after{width:70%}.stage[data-focused=true] iframe{transform:none}.stage[data-focused=true]:after{opacity:.72}}
`;

export const productDemoTemplate = `<style>${productDemoStyles}</style>
<button class="launch" type="button"><slot>See AI demo</slot></button>
<div class="shell" hidden role="dialog" aria-modal="true" aria-labelledby="pd-title" aria-describedby="pd-status"><section class="panel">
<header class="top"><div class="brand"><span class="mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3.5 13.7 9l5.8 1.7-5.8 1.7L12 18l-1.7-5.6-5.8-1.7L10.3 9Z" fill="currentColor"/></svg></span><span class="title" id="pd-title">Live AI product demo</span></div><div class="status-wrap"><span class="status-dot" aria-hidden="true"></span><span class="status" id="pd-status" role="status" aria-live="polite">Ready</span></div><button class="close" type="button" aria-label="Close demo"><svg viewBox="0 0 20 20"><path d="m5 5 10 10M15 5 5 15" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></button></header>
<main class="stage" aria-busy="false"><div class="empty"><div class="loader"><div class="loader-glyph" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 3.5 13.7 9l5.8 1.7-5.8 1.7L12 18l-1.7-5.6-5.8-1.7L10.3 9Z" fill="currentColor"/></svg></div><strong>Preparing your live demo</strong><p class="loader-copy">Creating a secure browser session…</p><div class="progress" aria-hidden="true"></div></div></div>
<div class="goal"><form novalidate><p class="kicker">Live product walkthrough</p><h2>What would you like to see?</h2><p class="copy">Describe a workflow and the AI will demonstrate it in a secure demo environment.</p><label class="label" for="pd-goal">Demo goal</label><input id="pd-goal" required minlength="3" maxlength="1000" autocomplete="off" placeholder="Show me how analytics filters work"><button class="primary goal-submit" type="submit"><span>Start live demo</span></button><p class="notice" role="alert" aria-live="assertive"></p></form></div></main>
<form class="composer"><input aria-label="Send an update" maxlength="1000" autocomplete="off" placeholder="Ask the demo to show something else" disabled><button class="send" type="submit" aria-label="Send update" disabled><svg viewBox="0 0 20 20"><path d="M10 15V4m0 0L5.5 8.5M10 4l4.5 4.5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg></button></form>
</section></div>`;
